words = [
    "allauth",
    "anymail",
    "atcb",
    "autoplay",
    "blockquote",
    "bluesky",
    "cmap",
    "csrfmiddlewaretoken",
    "dataid",
    "dateid",
    "dockerfile",
    "dokku",
    "elif",
    "endcomment",
    "endfor",
    "errorlist",
    "eventcalendar",
    "favicons",
    "fcm",
    "fieldsets",
    "formset",
    "imagekit",
    "innerhtml",
    "joinable",
    "lanczos",
    "linkedin",
    "livekit",
    "lookups",
    "modeladmin",
    "onboarded",
    "playsinline",
    "posthog",
    "pyright",
    "queryset",
    "signup",
    "staticfiles",
    "stylesheet",
    "taggit",
    "tailwindcss",
    "tblue",
    "tcreme",
    "tiedye",
    "tmauve",
    "totemcircles",
    "tpink",
    "tprose",
    "truetype",
    "truncatewords",
    "tshadow",
    "urlpatterns",
    "waitlist",
    "webflow",
    "wght",
    "woff",
]
